INSERT INTO quote (text, author) VALUES ('The best way to get started is to quit talking and begin doing.', 'Walt Disney');
INSERT INTO quote (text, author) VALUES ('Don’t let yesterday take up too much of today.', 'Will Rogers');
INSERT INTO quote (text, author) VALUES ('It’s not whether you get knocked down, it’s whether you get up.', 'Vince Lombardi');
INSERT INTO quote (text, author) VALUES ('If you are working on something exciting, it will keep you motivated.', 'Steve Jobs');
INSERT INTO quote (text, author) VALUES ('Success is not in what you have, but who you are.', 'Bo Bennett');
INSERT INTO quote (text, author) VALUES ('Hardships often prepare ordinary people for an extraordinary destiny.', 'C.S. Lewis');
INSERT INTO quote (text, author) VALUES ('Believe you can and you’re halfway there.', 'Theodore Roosevelt');
INSERT INTO quote (text, author) VALUES ('Act as if what you do makes a difference. It does.', 'William James');
INSERT INTO quote (text, author) VALUES ('Success is not final, failure is not fatal: It is the courage to continue that counts.', 'Winston Churchill');
INSERT INTO quote (text, author) VALUES ('Happiness is not something ready-made. It comes from your own actions.', 'Dalai Lama');
INSERT INTO quote (text, author) VALUES ('Do what you can with all you have, wherever you are.', 'Theodore Roosevelt');
INSERT INTO quote (text, author) VALUES ('Start where you are. Use what you have. Do what you can.', 'Arthur Ashe');
INSERT INTO quote (text, author) VALUES ('Dream big and dare to fail.', 'Norman Vaughan');
INSERT INTO quote (text, author) VALUES ('You miss 100% of the shots you don’t take.', 'Wayne Gretzky');
INSERT INTO quote (text, author) VALUES ('Don’t watch the clock; do what it does. Keep going.', 'Sam Levenson');
INSERT INTO quote (text, author) VALUES ('Everything you’ve ever wanted is on the other side of fear.', 'George Addair');
INSERT INTO quote (text, author) VALUES ('Opportunities don’t happen. You create them.', 'Chris Grosser');
INSERT INTO quote (text, author) VALUES ('Great things never come from comfort zones.', 'Anonymous');
INSERT INTO quote (text, author) VALUES ('Push yourself, because no one else is going to do it for you.', 'Anonymous');
INSERT INTO quote (text, author) VALUES ('Little things make big days.', 'Anonymous');
INSERT INTO quote (text, author) VALUES ('Don’t stop when you’re tired. Stop when you’re done.', 'Anonymous');
INSERT INTO quote (text, author) VALUES ('Wake up with determination. Go to bed with satisfaction.', 'Anonymous');
